const gbt9704Domains = [
  { id: "page", title: "纸张与版面", summary: "A4、页边、版心、行数和字数。" },
  { id: "base-text", title: "基础文字", summary: "默认字体字号、颜色和正文段落。" },
  { id: "header", title: "版头", summary: "份号、密级、紧急程度、发文机关标志、发文字号、签发人和红色分隔线。" },
  { id: "body", title: "主体", summary: "标题、主送机关、正文、附件说明、署名、成文日期和附注。" },
  { id: "attachment", title: "附件", summary: "附件另面编排、附件标题和附件正文格式。" },
  { id: "imprint", title: "版记", summary: "分隔线、抄送机关、印发机关和印发日期。" },
  { id: "page-number", title: "页码", summary: "页码字体、位置、单双页和一字线。" },
  { id: "landscape-table", title: "横排表格", summary: "横排表格页码位置和表头方向。" },
  { id: "special", title: "特定格式", summary: "信函、命令/令、纪要格式。" },
];

const gbt9704Rules = [
  {
    id: "page.a4-margins",
    domainId: "page",
    clause: "5.1, 5.2.1",
    title: "A4 幅面与版心尺寸",
    standard: "A4 210mm x 297mm；天头 37mm±1mm，订口 28mm±1mm，版心 156mm x 225mm。",
    severity: "critical",
    fixMode: "auto",
    fixAction: "page",
    payload: {
      pageSize: { widthMm: 210, heightMm: 297 },
      marginsMm: { top: 37, right: 26, bottom: 35, left: 28 },
    },
  },
  {
    id: "page.lines-chars",
    domainId: "page",
    clause: "5.2.3",
    title: "每面行数与每行字数",
    standard: "一般每面 22 行、每行 28 字，并撑满版心。",
    severity: "major",
    fixMode: "review",
  },
  {
    id: "text.default-font",
    domainId: "base-text",
    clause: "5.2.2, 5.2.4",
    title: "默认字体字号和颜色",
    standard: "如无特殊说明，公文格式各要素一般用 3 号仿宋体字，文字颜色为黑色。",
    severity: "critical",
    fixMode: "auto",
    fixAction: "body",
    payload: {
      fontFamily: "仿宋_GB2312",
      fallbackFonts: ["仿宋", "FangSong"],
      fontSizePt: 16,
      firstLineChars: 2,
      lineSpacingPt: 28,
      beforePt: 0,
      afterPt: 0,
    },
  },
  {
    id: "header.serial-security-urgency",
    domainId: "header",
    clause: "7.2.1-7.2.3",
    title: "份号、密级和紧急程度",
    standard: "份号、密级和紧急程度按规定位置和顺序自上而下分行排列。",
    severity: "major",
    fixMode: "confirm",
  },
  {
    id: "header.agency-mark",
    domainId: "header",
    clause: "7.2.4",
    title: "发文机关标志",
    standard: "居中排布，上边缘至版心上边缘 35mm，推荐红色小标宋体字。",
    severity: "critical",
    fixMode: "confirm",
  },
  {
    id: "header.issue-number",
    domainId: "header",
    clause: "7.2.5",
    title: "发文字号",
    standard: "编排在发文机关标志下空二行位置，年份用六角括号，序号不编虚位。",
    severity: "major",
    fixMode: "confirm",
  },
  {
    id: "header.red-rule",
    domainId: "header",
    clause: "7.2.7",
    title: "版头红色分隔线",
    standard: "发文字号之下 4mm 处居中印一条与版心等宽的红色分隔线。",
    severity: "critical",
    fixMode: "confirm",
  },
  {
    id: "body.title",
    domainId: "body",
    clause: "7.3.1",
    title: "公文标题",
    standard: "一般用 2 号小标宋体字，红色分隔线下空二行，居中排布，回行词意完整。",
    severity: "critical",
    fixMode: "auto",
    fixAction: "headings",
    payload: {
      documentTitle: { fontFamily: "方正小标宋简体", fallbackFonts: ["小标宋", "宋体"], fontSizePt: 22, alignment: "center" },
      levels: [
        { pattern: "^([一二三四五六七八九十]+、)", fontFamily: "黑体", fontSizePt: 16, bold: false },
        { pattern: "^（[一二三四五六七八九十]+）", fontFamily: "楷体_GB2312", fallbackFonts: ["楷体"], fontSizePt: 16, bold: false },
        { pattern: "^[0-9]+[．.、]", fontFamily: "仿宋_GB2312", fallbackFonts: ["仿宋"], fontSizePt: 16, bold: false },
        { pattern: "^（[0-9]+）", fontFamily: "仿宋_GB2312", fallbackFonts: ["仿宋"], fontSizePt: 16, bold: false },
      ],
    },
  },
  {
    id: "body.main-recipient",
    domainId: "body",
    clause: "7.3.2",
    title: "主送机关",
    standard: "标题下空一行，左顶格，回行仍顶格，最后一个机关名称后标全角冒号。",
    severity: "major",
    fixMode: "review",
  },
  {
    id: "body.paragraphs",
    domainId: "body",
    clause: "7.3.3",
    title: "正文段落和层级",
    standard: "首页必须显示正文；每个自然段左空二字，回行顶格；结构层级依次为 一、（一）1.（1）。",
    severity: "critical",
    fixMode: "auto",
    fixAction: "body",
  },
  {
    id: "body.signature-date",
    domainId: "body",
    clause: "7.3.5",
    title: "署名、成文日期和印章区",
    standard: "按加章、不加章、签名章分别编排；成文日期用阿拉伯数字标全年月日，月日不补零。",
    severity: "critical",
    fixMode: "confirm",
    fixAction: "signature",
    payload: {
      fontFamily: "仿宋_GB2312",
      fallbackFonts: ["仿宋"],
      fontSizePt: 16,
      alignment: "right",
    },
  },
  {
    id: "body.attachment-note",
    domainId: "body",
    clause: "7.3.4",
    title: "附件说明",
    standard: "正文下空一行左空二字编排，附件名称较长回行时与上一行附件名称首字对齐。",
    severity: "major",
    fixMode: "review",
  },
  {
    id: "attachment.layout",
    domainId: "attachment",
    clause: "7.3.7",
    title: "附件另面编排",
    standard: "附件另面编排并在版记之前；附件二字及顺序号 3 号黑体，附件标题居中，格式同正文。",
    severity: "major",
    fixMode: "confirm",
  },
  {
    id: "imprint.rules",
    domainId: "imprint",
    clause: "7.4.1",
    title: "版记分隔线",
    standard: "版记分隔线与版心等宽；首条和末条粗线推荐 0.35mm，中间细线推荐 0.25mm。",
    severity: "major",
    fixMode: "confirm",
  },
  {
    id: "imprint.copy-print",
    domainId: "imprint",
    clause: "7.4.2-7.4.3",
    title: "抄送机关、印发机关和印发日期",
    standard: "一般用 4 号仿宋体字，左右各空一字；印发日期用阿拉伯数字标全年月日。",
    severity: "major",
    fixMode: "confirm",
  },
  {
    id: "page-number.layout",
    domainId: "page-number",
    clause: "7.5",
    title: "页码",
    standard: "4 号半角宋体阿拉伯数字，版心下边缘之下 7mm；单页码居右空一字，双页码居左空一字，两侧加一字线。",
    severity: "major",
    fixMode: "confirm",
  },
  {
    id: "landscape-table.layout",
    domainId: "landscape-table",
    clause: "8",
    title: "横排表格",
    standard: "A4 横排表格页码位置与其他页码一致；单页码表头在订口一边，双页码表头在切口一边。",
    severity: "minor",
    fixMode: "confirm",
  },
  {
    id: "special.letter",
    domainId: "special",
    clause: "10.1",
    title: "信函格式",
    standard: "发文机关标志上边缘至上页边 30mm；上下红色双线；首页不显示页码。",
    severity: "major",
    fixMode: "confirm",
  },
  {
    id: "special.order",
    domainId: "special",
    clause: "10.2",
    title: "命令/令格式",
    standard: "发文机关标志由全称加“命令”或“令”组成，上边缘至版心上边缘 20mm。",
    severity: "major",
    fixMode: "confirm",
  },
  {
    id: "special.minutes",
    domainId: "special",
    clause: "10.3",
    title: "纪要格式",
    standard: "纪要标志居中，上边缘至版心上边缘 35mm；出席、请假、列席人员名单按规定编排。",
    severity: "major",
    fixMode: "confirm",
  },
];

const gbt9704Standard = {
  id: "gbt-9704-2012",
  name: "GB/T 9704-2012 党政机关公文格式",
  source: "公文标准.pdf",
  domains: gbt9704Domains,
  rules: gbt9704Rules,
};

function getGbt9704Rule(ruleId) {
  return gbt9704Rules.find((rule) => rule.id === ruleId) || null;
}

export { gbt9704Standard, getGbt9704Rule };
